language: python
python:
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls coverage
  - pip install pytest --upgrade
script:
  - python setup.py install
  - coverage run --source flask_rest_jsonapi -m pytest -v
after_success:
  - coveralls
